name: "Test"
author: "hugoalh"
description: "Test."
runs:
  using: "composite"
  steps:
    - name: "Execute Main Action"
      run: |
        ${{github.action_path}}/main.ps1
      shell: "pwsh"
branding:
  icon: "activity"
  color: "red"
