# $<Schema>$ https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: "Scan Virus"
author: "hugoalh"
description: "Scan virus in the GitHub Action runner workspace."
inputs:
  gitdepth:
    description: "{boolean} Also scan every Git commits."
    required: false
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "shield"
  color: "red"
