# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: "Test"
author: "hugoalh"
description: "Test."
runs:
  using: "composite"
  steps:
    - uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@main"
      with:
        allowprerelease: "True"
    - run: |
        Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
        [String]$FilePath = Join-Path -Path $Env:GITHUB_WORKSPACE -ChildPath 'test.txt'
        If ($Null -ne (Restore-GitHubActionsCache -Path @($Env:GITHUB_WORKSPACE) -Key @('test'))) {
          Get-Content -LiteralPath $FilePath -Encoding 'UTF8NoBOM'
        }
        Set-Content -LiteralPath $FilePath -Value (New-Guid).Guid -PassThru -Force -Confirm:$False -Encoding 'UTF8NoBOM'
        Save-GitHubActionsCache -Path @($Env:GITHUB_WORKSPACE) -Key 'test'
        Export-GitHubActionsArtifact -Name 'test' -LiteralPath @($Env:GITHUB_WORKSPACE) -RootDirectory $Env:GITHUB_WORKSPACE
      shell: "pwsh"
branding:
  icon: "package"
  color: "gray-dark"