# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
on:
  workflow_dispatch:
jobs:
  main:
    strategy:
      matrix:
        runs-on:
          - "macos-latest"
          - "ubuntu-latest"
          - "windows-latest"
      fail-fast: false
    permissions: {}
    runs-on: "${{matrix.runs-on}}"
    steps:
      - shell: "pwsh"
        run: |-
          Get-PSDrive
