on:
  workflow_dispatch:
defaults:
  run:
    shell: "pwsh"
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "denoland/setup-deno@v1.1.2"
      - run: |
          echo "const kv = await Deno.openKv(Deno.env.get("GITHUB_WORKSPACE")); await kv.set(["users", "alice"], { name: "Alice" }); const res = await kv.get(["users", "alice"]); console.log(res.key); console.log(res.value);" > "$RUNNER_TEMP/qwerty.ts"
          deno run --allow-all "$RUNNER_TEMP/qwerty.ts"
      - uses: "actions/upload-artifact@v3.1.2"
        with:
          path: "${{github.workspace}}"
