on:
  workflow_dispatch:
defaults:
  run:
    shell: "pwsh"
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@main"
      - run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit\module\internal\new-random-token.psm1' -Scope 'Local'
          New-RandomToken
