on:
  workflow_dispatch:
defaults:
  run:
    shell: "pwsh"
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@main"
        with:
          allowprerelease: "True"
      - run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          Write-GitHubActionsNotice -Message ('1234567890' * 500) -Summary '::test::'
