on:
  workflow_dispatch:
defaults:
  run:
    shell: "pwsh"
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@main"
        with:
          allowprerelease: "True"
      - run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          Write-GitHubActionsNotice -Message "::notice::$('1234567890' * 500)" -Summary 'Test'
          Write-GitHubActionsDebug -Message 'Hello, world!' -SkipEmptyMessage
          Write-GitHubActionsDebug -Message 'Hello, world!' -SkipEmptyMessage -PassThru
