on:
  workflow_dispatch:
defaults:
  run:
    shell: "pwsh"
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@main"
        with:
          version: "1.0.69"
      - run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          Get-GitHubActionsIsDebug
