on:
  workflow_dispatch:
defaults:
  run:
    shell: "pwsh"
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@main"
      - run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          Write-GitHubActionsError -Message ('1--------10--------20--------30--------40--------50--------60--------70--------80--------90--------100' + ('-------10--------20--------30--------40--------50--------60--------70--------80--------90--------100' * 4000))
