on:
  workflow_dispatch:
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - run: |
          @('GITHUB_ENV', 'GITHUB_EVENT_PATH', 'GITHUB_OUTPUT', 'GITHUB_PATH', 'GITHUB_STATE', 'GITHUB_STEP_SUMMARY', 'GITHUB_WORKSPACE') |
            ForEach-Object -Process {
              Write-Host -Object "$($_): $(Test-Path -LiteralPath (Get-Content -Path "Env:\$($_)"))"
            }
        shell: "pwsh"
