on:
  workflow_dispatch:
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - run: |
          Write-Host -Object '::group::'
          Write-Host -Object 'foo bar'
          Write-Host -Object '::endgroup::'
        shell: "pwsh"
