# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - run: |
          Get-Content -LiteralPath $Env:GITHUB_OUTPUT
        shell: "pwsh"
