name: "Discord"
on:
  workflow_dispatch:
jobs:
  discord:
    name: "Discord"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh/send-discord-webhook-ghaction@main"
        with:
          key: "${{secrets.DISCORDWEBHOOK_HUGOALHSTUDIO_TEST}}"
          payload: |
            {
              "content": "Hello, world!"
            }
