on:
  workflow_dispatch:
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh/trigger-ifttt-webhook-applet-ghaction@main"
        with:
          eventname: "test"
          key: "${{secrets.IFTTT}}"
