# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "IFTTT"
on:
  workflow_dispatch:
jobs:
  ifttt:
    name: "IFTTT"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh/trigger-ifttt-webhook-applet-ghaction/use-powershell@main"
        with:
          eventname: "debug"
          key: "foobar"
          payload: |
            {
              "value1": "Hello, world!"
            }
          dryrun: "true"
