# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "One"
on:
  workflow_dispatch:
jobs:
  main:
    name: "Main"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2.3.4"
      - name: "Get Package Name"
        id: "get-package-name"
        run: "Write-Output \"::set-output name=value::$(Get-Content .\\package.json -Encoding UTF8 -Raw | ConvertFrom-Json | Select -ExpandProperty name)\""
        shell: "pwsh"
      - name: "Get Package Version"
        id: "get-package-version"
        run: "Write-Output \"::set-output name=value::$(Get-Content .\\package.json -Encoding UTF8 -Raw | ConvertFrom-Json | Select -ExpandProperty version)\""
        shell: "pwsh"
      - name: "Recall"
        run: "echo \"${{steps.get-package-name.outputs.value}}@${{steps.get-package-version.outputs.value}}\""
        shell: "bash"
