# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "One"
on:
  workflow_dispatch:
jobs:
  main:
    name: "Main"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2.3.5"
      - name: "Test"
        run: |
          $packageContent = (Get-Content -Path .\package.json -Encoding utf8NoBOM -Raw)
          $packageOriginalName = (ConvertFrom-Json -InputObject $packageContent | Select-Object -ExpandProperty name)
          Write-Output -InputObject "$(($packageContent).Replace($packageOriginalName, "@${{github.repository}}"))"
        shell: "pwsh"
