# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "One"
on:
  workflow_dispatch:
jobs:
  main:
    name: "Main"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Setup NodeJS"
        uses: "actions/setup-node@v2.4.1"
      - name: "Test"
        id: "test"
        uses: "hugoalh/replaceholder-ghaction/use-nodejs@main"
        with:
          target: |
            external: "%external%"
            payload: "%payload%"
          list_external: |
            foo: "bar"
            number: 10
      - name: "Recall"
        run: "echo ${{steps.test.outputs.result}}"
