on:
  workflow_dispatch:
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@main"
        with:
          toolkit_version: "1.3.0"
      - run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          Get-GitHubActionsWebhookEventPayload
          Get-GitHubActionsWorkflowRunUri
          Test-GitHubActionsEnvironment
        shell: "pwsh"
