on:
  workflow_dispatch:
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@main"
        with:
          toolkit_version: "1.3.0"
      - run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          Restore-GitHubActionsCache -Key @('test') -LiteralPath $Env:GITHUB_WORKSPACE
        shell: "pwsh"
