name: "Test"
on:
  workflow_dispatch:
jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - run: |
          Add-Content -LiteralPath $env:GITHUB_ENV -Value 'FOO=bar' -Confirm:$false -Encoding 'UTF8NoBOM'
          '-----'
          Get-Content -LiteralPath $env:GITHUB_ENV -Raw -Encoding 'UTF8NoBOM'
        shell: "pwsh"
