name: "Test"
on:
  workflow_dispatch:
defaults:
  run:
    shell: "pwsh"
jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.0.2"
        with:
          fetch-depth: 0
      - uses: "hugoalh/github-laboratory@main"
