on:
  workflow_dispatch:
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - run: |
          "CI: $($Env:CI -ine 'true')"
          "GITHUB_ACTION_REPOSITORY: $([String]::IsNullOrWhiteSpace($Env:GITHUB_ACTION_REPOSITORY))"
          "GITHUB_ACTION: $([String]::IsNullOrWhiteSpace($Env:GITHUB_ACTION))"
          "GITHUB_ACTIONS: $([String]::IsNullOrWhiteSpace($Env:GITHUB_ACTIONS))"
          "GITHUB_ACTOR_ID: $([String]::IsNullOrWhiteSpace($Env:GITHUB_ACTOR_ID))"
          "GITHUB_ACTOR: $([String]::IsNullOrWhiteSpace($Env:GITHUB_ACTOR))"
          "GITHUB_API_URL: $([String]::IsNullOrWhiteSpace($Env:GITHUB_API_URL))"
          "GITHUB_ENV: $([String]::IsNullOrWhiteSpace($Env:GITHUB_ENV))"
          "GITHUB_EVENT_NAME: $([String]::IsNullOrWhiteSpace($Env:GITHUB_EVENT_NAME))"
          "GITHUB_EVENT_PATH: $([String]::IsNullOrWhiteSpace($Env:GITHUB_EVENT_PATH))"
          "GITHUB_GRAPHQL_URL: $([String]::IsNullOrWhiteSpace($Env:GITHUB_GRAPHQL_URL))"
          "GITHUB_JOB: $([String]::IsNullOrWhiteSpace($Env:GITHUB_JOB))"
          "GITHUB_PATH: $([String]::IsNullOrWhiteSpace($Env:GITHUB_PATH))"
          "GITHUB_REF_NAME: $([String]::IsNullOrWhiteSpace($Env:GITHUB_REF_NAME))"
          "GITHUB_REF_PROTECTED: $([String]::IsNullOrWhiteSpace($Env:GITHUB_REF_PROTECTED))"
          "GITHUB_REF_TYPE: $([String]::IsNullOrWhiteSpace($Env:GITHUB_REF_TYPE))"
          "GITHUB_REPOSITORY_ID: $([String]::IsNullOrWhiteSpace($Env:GITHUB_REPOSITORY_ID))"
          "GITHUB_REPOSITORY_OWNER_ID: $([String]::IsNullOrWhiteSpace($Env:GITHUB_REPOSITORY_OWNER_ID))"
          "GITHUB_REPOSITORY_OWNER: $([String]::IsNullOrWhiteSpace($Env:GITHUB_REPOSITORY_OWNER))"
          "GITHUB_REPOSITORY: $([String]::IsNullOrWhiteSpace($Env:GITHUB_REPOSITORY))"
          "GITHUB_RUN_ATTEMPT: $([String]::IsNullOrWhiteSpace($Env:GITHUB_RUN_ATTEMPT))"
          "GITHUB_RUN_ID: $([String]::IsNullOrWhiteSpace($Env:GITHUB_RUN_ID))"
          "GITHUB_RUN_NUMBER: $([String]::IsNullOrWhiteSpace($Env:GITHUB_RUN_NUMBER))"
          "GITHUB_SERVER_URL: $([String]::IsNullOrWhiteSpace($Env:GITHUB_SERVER_URL))"
          "GITHUB_SHA: $([String]::IsNullOrWhiteSpace($Env:GITHUB_SHA))"
          "GITHUB_WORKFLOW_REF: $([String]::IsNullOrWhiteSpace($Env:GITHUB_WORKFLOW_REF))"
          "GITHUB_WORKFLOW_SHA: $([String]::IsNullOrWhiteSpace($Env:GITHUB_WORKFLOW_SHA))"
          "GITHUB_WORKFLOW: $([String]::IsNullOrWhiteSpace($Env:GITHUB_WORKFLOW))"
          "GITHUB_WORKSPACE: $([String]::IsNullOrWhiteSpace($Env:GITHUB_WORKSPACE))"
          "RUNNER_ARCH: $([String]::IsNullOrWhiteSpace($Env:RUNNER_ARCH))"
          "RUNNER_NAME: $([String]::IsNullOrWhiteSpace($Env:RUNNER_NAME))"
          "RUNNER_OS: $([String]::IsNullOrWhiteSpace($Env:RUNNER_OS))"
          "RUNNER_TEMP: $([String]::IsNullOrWhiteSpace($Env:RUNNER_TEMP))"
          "ACTIONS_RUNTIME_TOKEN: $([String]::IsNullOrWhiteSpace($Env:ACTIONS_RUNTIME_TOKEN))"
          "ACTIONS_RUNTIME_URL: $([String]::IsNullOrWhiteSpace($Env:ACTIONS_RUNTIME_URL))"
          "GITHUB_RETENTION_DAYS: $([String]::IsNullOrWhiteSpace($Env:GITHUB_RETENTION_DAYS))"
          "ACTIONS_CACHE_URL: $([String]::IsNullOrWhiteSpace($Env:ACTIONS_CACHE_URL))"
          "ACTIONS_ID_TOKEN_REQUEST_TOKEN: $([String]::IsNullOrWhiteSpace($Env:ACTIONS_ID_TOKEN_REQUEST_TOKEN))"
          "ACTIONS_ID_TOKEN_REQUEST_URL: $([String]::IsNullOrWhiteSpace($Env:ACTIONS_ID_TOKEN_REQUEST_URL))"
          "GITHUB_STEP_SUMMARY: $([String]::IsNullOrWhiteSpace($Env:GITHUB_STEP_SUMMARY))"
          "RUNNER_TOOL_CACHE: $([String]::IsNullOrWhiteSpace($Env:RUNNER_TOOL_CACHE))"
        shell: "pwsh"
