on:
  workflow_dispatch:
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Setup NodeJS"
        uses: "actions/setup-node@v3.6.0"
        with:
          node-version: "lts/*"
          check-latest: true
          registry-url: "https://registry.npmjs.org/"
      - uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@main"
        with:
          toolkit_version: "1.3.2-beta2"
          toolkit_allowprerelease: "True"
      - run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          Restore-GitHubActionsCache -Key @('test') -LiteralPath $Env:GITHUB_WORKSPACE
        shell: "pwsh"
