on:
  workflow_dispatch:
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - run: |
          $Env:CI -ine 'true'
          [String]::IsNullOrWhiteSpace($Env:GITHUB_ACTION_REPOSITORY)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_ACTION)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_ACTIONS)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_ACTOR_ID)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_ACTOR)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_API_URL)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_ENV)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_EVENT_NAME)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_EVENT_PATH)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_GRAPHQL_URL)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_JOB)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_PATH)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_REF_NAME)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_REF_PROTECTED)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_REF_TYPE)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_REPOSITORY_ID)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_REPOSITORY_OWNER_ID)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_REPOSITORY_OWNER)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_REPOSITORY)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_RUN_ATTEMPT)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_RUN_ID)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_RUN_NUMBER)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_SERVER_URL)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_SHA)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_WORKFLOW_REF)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_WORKFLOW_SHA)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_WORKFLOW)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_WORKSPACE)
          [String]::IsNullOrWhiteSpace($Env:RUNNER_ARCH)
          [String]::IsNullOrWhiteSpace($Env:RUNNER_NAME)
          [String]::IsNullOrWhiteSpace($Env:RUNNER_OS)
          [String]::IsNullOrWhiteSpace($Env:RUNNER_TEMP)
          [String]::IsNullOrWhiteSpace($Env:ACTIONS_RUNTIME_TOKEN)
          [String]::IsNullOrWhiteSpace($Env:ACTIONS_RUNTIME_URL)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_RETENTION_DAYS)
          [String]::IsNullOrWhiteSpace($Env:ACTIONS_CACHE_URL)
          [String]::IsNullOrWhiteSpace($Env:ACTIONS_ID_TOKEN_REQUEST_TOKEN)
          [String]::IsNullOrWhiteSpace($Env:ACTIONS_ID_TOKEN_REQUEST_URL)
          [String]::IsNullOrWhiteSpace($Env:GITHUB_STEP_SUMMARY)
          [String]::IsNullOrWhiteSpace($Env:RUNNER_TOOL_CACHE)
        shell: "pwsh"
