name: "Test"
on:
  workflow_dispatch:
jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - run: |
          Write-Host -Object "::notice title=Foo=Bar::qwerty"
        shell: "pwsh"
